SET search_path TO gtournoi;


-- Schema

DROP SCHEMA IF EXISTS gtournoi CASCADE;
CREATE SCHEMA gtournoi AUTHORIZATION gtournoi;
GRANT ALL PRIVILEGES ON SCHEMA gtournoi TO gtournoi;


-- Tables

------------------------------------------------------------
-- Table: utilisateur
------------------------------------------------------------

CREATE TABLE utilisateur (
	idutilisateur		INT				GENERATED BY DEFAULT AS IDENTITY,
	pseudo			VARCHAR(25)		NOT NULL,
	motdepasse		VARCHAR(25) 	NOT NULL,
	role			INT				NOT NULL,
	CHECK (role IN (0, 1)),
	PRIMARY KEY (idutilisateur),
	UNIQUE (pseudo)
)WITHOUT OIDS;

------------------------------------------------------------
-- Table: joueur
------------------------------------------------------------

CREATE TABLE Joueur(
        id_joueur    INT  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        nom          VARCHAR(50) NOT NULL ,
        nationalite  VARCHAR(50) NOT NULL ,
        classemmentMondial INT NOT NULL ,
        sexe         VARCHAR(10) NOT NULL,
        image		 VARCHAR(20) NOT NULL,
        CONSTRAINT Joueur_PK PRIMARY KEY (id_joueur)
)WITHOUT OIDS;

------------------------------------------------------------
-- Table: t_match
------------------------------------------------------------

CREATE TABLE t_match(
        id_match    INT  GENERATED BY DEFAULT AS IDENTITY  NOT NULL ,
        heure    Date NOT NULL,
        courtDeTerrain VARCHAR(10) NOT NULL ,
        score   INT NOT NULL ,
        duree   Time NOT NULL,
        statut  VARCHAR(10) NOT NULL,
        nombreDeSet INT NOT NULL, 
        categorie VARCHAR(20) NOT NULL,

        id_joueur INT NOT NULL
	,CONSTRAINT Match_PK PRIMARY KEY (id_match)

	,CONSTRAINT Match_Joueur_FK FOREIGN KEY (id_joueur) REFERENCES Joueur(id_joueur)
)WITHOUT OIDS;

------------------------------------------------------------
-- Table: Equipe
------------------------------------------------------------

CREATE TABLE Equipe(
        id_equipe INT GENERATED BY DEFAULT AS IDENTITY NOT NULL ,
 
        id_joueur INT NOT NULL
         
	,CONSTRAINT Equipe_PK PRIMARY KEY (id_equipe)

	,CONSTRAINT Equipe_Joueur_FK FOREIGN KEY (id_joueur) REFERENCES Joueur(id_joueur)
)WITHOUT OIDS;

------------------------------------------------------------
-- Table: Arbitre
------------------------------------------------------------

CREATE TABLE Arbitre(
			id_arbitre INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
			nom VARCHAR(20) NOT NULL, 
			nationalite VARCHAR(20) NOT NULL 
			
		, CONSTRAINT Arbitre_PK PRIMARY KEY (id_arbitre)
)WITHOUT OIDS;

------------------------------------------------------------
-- Table: SousTournoi
------------------------------------------------------------


CREATE TABLE SousTournoi(
			id_soust INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            categorie VARCHAR(20) NOT NULL,
		    id_match INT NOT NULL			
			
			, CONSTRAINT SousTournoi_PK PRIMARY KEY (id_soust)
            , CONSTRAINT SousTournoi_Match_FK FOREIGN KEY (id_match) REFERENCES t_match(id_match)
)WITHOUT OIDS;

------------------------------------------------------------
-- Table: Journaliste
------------------------------------------------------------


CREATE TABLE Journaliste(
			id_journaliste INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
			nom VARCHAR(20) NOT NULL
			
		, CONSTRAINT Journaliste_PK PRIMARY KEY (id_journaliste)
)WITHOUT OIDS;
